Add controllers
mikadim/java-shareit pull request #2
Opened 2023-02-23 22:21 UTC by mikadim

2023-02-24 08:33 UTC, Frilock requested changes
Добрый день, хорошая в целом работа, критики нет, оставил пару комментариев, где на мой взгляд, можно улучшить код. Жду новую версию.

2023-02-24 08:33 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ResponseEntity<ItemDto> createItem(@RequestHeader("X-Sharer-User-Id") @NotNull Long userId,
литерал - X-Sharer-User-Id, повторяется более 3х раз, его нужно сделать константным полем класса (private static final ....)

2023-02-24 08:33 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/repository/InMemoryItemRepository.java
> +                        (i.getName().trim().toLowerCase().contains(prepText) || i.getDescription().trim().toLowerCase().contains(prepText)))
Можно использовать StringUtils.containsIgnoreCase(...)

2023-02-24 08:33 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +                dto.getDescription() == null || dto.getDescription().isBlank()) {
Можно использовать StringUtils.isBlank/isNotBlank

2023-02-24 08:33 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (dto.getAvailable() == null || dto.getAvailable().equals(false) ||
Можно использовать BoaleanUtils.isFalse

2023-02-24 08:33 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/UserErrorHandler.java
> +class UserErrorHandler {
А почему бы одним обработчиком не обойтись? По идее вы же не будете под каждый контроллер свой обработчик делать? По идее смысла особого в этом нет

2023-02-25 19:41 UTC, mikadim commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ResponseEntity<ItemDto> createItem(@RequestHeader("X-Sharer-User-Id") @NotNull Long userId,
Доброго времени! принято

2023-02-25 20:03 UTC, mikadim commented on src/main/java/ru/practicum/shareit/item/repository/InMemoryItemRepository.java
> +                        (i.getName().trim().toLowerCase().contains(prepText) || i.getDescription().trim().toLowerCase().contains(prepText)))
спс!

2023-02-25 20:20 UTC, mikadim commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (dto.getAvailable() == null || dto.getAvailable().equals(false) ||
да, так оно лучше выглядит. У меня кстати была идея добавить еще DTO под create, в котором повесить нужные проверки на поля. Но не понятно было нормальная ли это практика... оказывается вполне - https://www.baeldung.com/java-dto-pattern

2023-02-25 21:25 UTC, mikadim commented on src/main/java/ru/practicum/shareit/user/UserErrorHandler.java
> +class UserErrorHandler {
а непонятно предполагает ли такая структура общие пакеты, мысля такая тоже была... в теории написано - В этом модуле вы будете использовать структуру не по типам классов, а по фичам (англ. Feature layout) — весь код для работы с определённой сущностью должен быть в одном пакете. Поэтому сразу создайте четыре пакета — item, booking, request и user. В каждом из этих пакетов будут свои контроллеры, сервисы, репозитории и другие классы, которые вам понадобятся в ходе разработки.

2023-02-26 08:40 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/UserErrorHandler.java
> +class UserErrorHandler {
Ну в целом имеет место и такая реализация, окей.

2023-02-26 08:41 UTC, Frilock approved these changes
Принято

2023-02-26 08:41 UTC, Frilock commented on pom.xml
> +            <version>3.12.0</version>
Версию правильнее в properties выносить, чтобы проще было ее менять

2023-02-26 08:41 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/repository/InMemoryItemRepository.java
> +        final String prepText = text.trim();
prep лучше не сокращать - prepareTest, или что то такое

2023-02-26 21:40 UTC, mikadim commented on pom.xml
> +            <version>3.12.0</version>
исправилсо

2023-02-26 21:40 UTC, merged