Add bookings
mikadim/java-shareit pull request #3
Opened 2023-03-06 02:38 UTC by mikadim

add-bookings

2023-03-06 06:36 UTC, Frilock requested changes
Добрый день, написал ряд комментариев, на некоторые жду от Вас ответ, почему именно так решили сделать.

2023-03-06 06:36 UTC, Frilock commented on pom.xml
> +            <version>2.7.5</version>
А тут чего версию не вынесли? Да и версия спринга автоматически подтянется из parent

2023-03-06 06:36 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    BookingService bookingService;
Модификатор?

2023-03-06 06:36 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    public BookingController(BookingService bookingService, BookingMapper bookingMapper) {
Вы аннотацию @RequiredArgsConstructor ставите, зачем тогда конструктор явно создаете?

2023-03-06 06:36 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    @GetMapping()
Пустые скобки не нужны

2023-03-06 06:36 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +    Long itemId;
Модификаторы? Проверьте другие места, больше не буду о этой проблеме писать

2023-03-06 06:36 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +@Table(name = "bookings", schema = "public")
public дефолтное значение, схему можно не указывать. Вам IDEA серым должна подсвечивать по идее

2023-03-06 06:36 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    @Id@GeneratedValue(strategy = GenerationType.IDENTITY)
Аннотации на одной строке не пишут

2023-03-06 06:36 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    public List<BookingForItemDto> findByItemId(Long itemId, Long userId);
Данный запрос довольно простой, Вам по идее нужно избегать аннотации Query по возможности, и стараться помаксимуму укладывать запрос в названии метода. Это нужно для того, чтобы избежать ситуации, когда вы решите поменять БД, и Вам придется переписывать запросы.

2023-03-06 06:36 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (booking.getStatus().equals(ItemStatus.APPROVED)) {
enum поля правильнее сравнивать через стандартные операторы != и ==, работать будет в любом случае, но стандартные операторы как минимум быстрее

2023-03-06 06:36 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        for (Booking b : bookings) {
Лучше просто booking, вместо b

2023-03-06 06:36 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/repository/UserRepositoryImpl.java
> +    public UserRepositoryImpl(@Lazy UserRepositoryJpa userRepositoryJpa) {
Зачем Вам аннотация Lazy?

2023-03-06 06:36 UTC, Frilock commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS public.bookings (
public не надо, это дефолтная схема

2023-03-06 06:36 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/dto/BookingForItemDto.java
> +public interface BookingForItemDto {
Как то мудрено, зачем ДТО через интерфейс делать?

2023-03-06 19:52 UTC, mikadim commented on pom.xml
> +            <version>2.7.5</version>
Добрый день! да, сначала так и сделал, но не стартовал спринг, прописал версию на попробовать и все стартануло (забыл перетащить потом в пропертиз). Делал инвалидейт кэш, и в r2 какие то классы убирал ничего не помогало. А так в стартере должна быть совместимая версия.
В общем закинул в пропертиз.

2023-03-06 20:02 UTC, mikadim commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    public BookingController(BookingService bookingService, BookingMapper bookingMapper) {
не нужен явно, я тут что то химичил с мапперами... поэтому и про модификатор выше забыл
убрал конструктор

2023-03-06 20:14 UTC, mikadim commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +    Long itemId;
кааааааааааааюсь! 
да, что то я новым дто не поставил private, признаю)

2023-03-06 20:19 UTC, mikadim commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +@Table(name = "bookings", schema = "public")
на всякий случай указал, idea не подсвечивает
убрал если что

2023-03-06 20:30 UTC, mikadim commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    public List<BookingForItemDto> findByItemId(Long itemId, Long userId);
да, я понял эту фишку, а нативные лучше вобще в крайнем случае
ок, поменял

2023-03-06 20:46 UTC, mikadim commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        for (Booking b : bookings) {
учтемс, мне то так проще, а когда читаешь видимо не очень
поправил, много где так было

2023-03-06 20:54 UTC, mikadim commented on src/main/java/ru/practicum/shareit/user/repository/UserRepositoryImpl.java
> +    public UserRepositoryImpl(@Lazy UserRepositoryJpa userRepositoryJpa) {
у меня ж тогда не будут доступны методы из JpaRepository? насколько понял из практикума здесь
public interface UserRepositoryJpa extends JpaRepository<User, Long> {
}
не будет создан бин с реализацией SimpleJpaRepository, и мы как раз говорим что надо сделать ее, не?

2023-03-06 21:01 UTC, mikadim commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (booking.getStatus().equals(ItemStatus.APPROVED)) {
принято

2023-03-06 21:07 UTC, mikadim commented on src/main/java/ru/practicum/shareit/booking/dto/BookingForItemDto.java
> +public interface BookingForItemDto {
хм, во-первых хотел попробовать как работают проекции, в практикуме маловато инфы было
во-вторых мне понравилось как работают)
я же эту проекцию использую потом чтобы отдать на слой представления и это то что будет видеть на фронте юзер - насоклько понял механизм проекций как раз для этого
или нет? почемe плохо?

2023-03-07 06:15 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/repository/UserRepositoryImpl.java
> +    public UserRepositoryImpl(@Lazy UserRepositoryJpa userRepositoryJpa) {
А вы смотрели без аннотации Lazy? У Вас не работало?
Вообще и без данной аннотации должно все доступно быть

2023-03-07 06:16 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/dto/BookingForItemDto.java
> +public interface BookingForItemDto {
Не очень понял про механизм проекции, можно поподробнее? Почему обычным классом ДТО не обойтись было?

2023-03-07 06:18 UTC, Frilock requested changes
Добрый день, я оставил Вам комментарии на ваши ответы. Напишите мне лучше в пачку, обсудим, а то пара вещей не очень понятна.
Кстати, не знаю, советовал или нет, но можете себе в IDEA установить плагин sonarlint, статический анализатор кода, который покажет ряд хороших практик и возможные места с ошибками

2023-03-10 13:57 UTC, Frilock approved these changes
Принято

2023-03-16 23:21 UTC, merged