Add docker
mikadim/java-shareit pull request #5
Opened 2023-03-26 14:12 UTC by mikadim

2023-03-27 05:54 UTC, Frilock requested changes
Добрый день, не до конца выполнено ТЗ, зависимости валидации не должно быть в подмодуле сервера. Кроме того, оставил общую просьбу по организации многомодульных проектов.

2023-03-27 05:54 UTC, Frilock commented on server/pom.xml
> +            <artifactId>spring-boot-starter-validation</artifactId>
Данная зависимость должна отсутствовать в pom файле подмодуля server, поскольку вся валидация входных данных должна быть перенесена в gateway

2023-03-27 05:54 UTC, Frilock commented on server/pom.xml
> +            <version>${mapstruct.version}</version>
Общий комментарий по pom файлам. Смотрите, у Вас многомодульный проект, сейчас он состоит из 2х модулей, но возможно их будет больше. Так вот, хочется чтобы в приложении была одна точка добавления зависимостей. Такой обычно делают корневой pom файл. Там нужно сделать блок dependencyManager и добавлять те библиотеки которых нет в parent, а затем уже в других pom файлах подключать, но уже без указания версии.

2023-03-27 22:12 UTC, mikadim commented on server/pom.xml
> +            <version>${mapstruct.version}</version>
как раз в этом спринте мелькала перед глазами эта тема
навел порядок в помах

2023-03-28 23:12 UTC, mikadim commented on server/pom.xml
> +            <artifactId>spring-boot-starter-validation</artifactId>
годно
все лишнее убрал, тесты на валидацию закинул в gateway, тесты маппинга оставил на месте

2023-03-29 14:11 UTC, Frilock approved these changes
Принял, но 2 мелких комментария оставил, посмотрите.

2023-03-29 14:11 UTC, Frilock commented on gateway/src/main/java/ru/practicum/shareit/item/ItemController.java
> +    static final String USER_ID_TAG = "X-Sharer-User-Id";
Зачем private убрали? Если используется где то в пакете, то лучше protected поставьте

2023-03-29 14:11 UTC, Frilock commented on pom.xml
> +                <version>4.5.2</version>
Сами номера версий нужно в properties вынести

2023-04-02 11:01 UTC, mikadim commented on pom.xml
> +                <version>4.5.2</version>
исправил

2023-04-02 11:08 UTC, mikadim commented on gateway/src/main/java/ru/practicum/shareit/item/ItemController.java
> +    static final String USER_ID_TAG = "X-Sharer-User-Id";
да, в тесте понадобилась, спс за подсказку исправил

2023-04-02 11:09 UTC, merged